version: '3.8'

services:
  evolution_api:
    image: evoapicloud/evolution-api:v2.1.1
    container_name: evolution_api_yakobarber
    ports:
      - "8085:8080"
    volumes:
      - evolution_instances:/evolution/instances
    environment:
      - AUTHENTICATION_API_KEY=EmaNaon2026SecretoMaster
    env_file:
      - .env
    networks:
      - yakobarber_net
    depends_on:
      - evolution_redis

  evolution_redis:
    image: redis:alpine
    container_name: evolution_redis
    networks:
      - yakobarber_net

volumes:
  evolution_instances:

networks:
  yakobarber_net:
    name: yakobarber_shared_network